### ISSUE TITLE
I have got "OSError: ./TR1000.txt not found." 

### ISSUE THREAD

**Issue by Alienvoid** [Joey777210/visibility_estimation#1]
But there is no such file in this repository. What can I do?

**Comment by Joey777210** [comment]
You can find this File "TR1000.txt" in danaBerman's repository.
https://github.com/danaberman/non-local-dehazing

**Comment by Alienvoid** [comment]
Thanks for your solution. I have found the file.

**Comment by Joey777210** [comment]
The file "TR1000.txt" is added in this repository.
