### ISSUE TITLE
Library versioning problem, as it seems

### ISSUE THREAD

**Issue by brigr** [Joey777210/visibility_estimation#2]
Hi,

Thank you for publishing this Python implementation. I would like to ask which Python interpreter version and which versions of the Python dependencies which are listed in README.md were used while main.py was in development and testing.

I am trying to run main.py either with Python 2 (v2.7.15) and Python 3 (v3.6.3), but I get something like the following:

Traceback (most recent call last):
  File "main.py", line 324, in <module>
    main()
  File "main.py", line 311, in main
    transmission_estimission = non_local_transmission(img_gray, air)
  File "main.py", line 178, in non_local_transmission
    transmission = wls_filter(trans, data_term_weight, img_hazy_corrected.astype(np.float32), lambd)
  File "main.py", line 206, in wls_filter
    we = np.pad(temp, ([0, 0], [h, 0]))[0]
TypeError: pad() missing 1 required positional argument: 'mode'

It seems to me that the versions of the Python library dependencies do matter for someone to be able to run the script. Is it possible to publish the library versions and Python interpreter version which were used to test the script?

**Comment by Joey777210** [comment]
Thanks for this issue. I have publish the versions of dependencies I used. If that helps you, plz let me know.
Have a nice day.

**Comment by brigr** [comment]
To Joey777210:

Yes, the versions of the dependencies that you published worked for me successfully. By reverting my library versions to the ones you published, the script worked and computed ouput. By this, I assume that the script works as-is on my system as expected or without a major problem.
